set -g mouse on
set -g history-limit 10000

# True color setting
set -g default-terminal "$TERM"
set -ag terminal-overrides ",$TERM:Tc"

# Active pane border highlight
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour39
